site_name: CCPacks documentation

nav: 
    - Home: index.md
    - Blocks: blocks.md
    - Items:
      - Armor: armor.md
      - General: item/general.md
      - Food: item/food.md
      - Tools: item/tools.md
      - Wapons: item/weapons.md


theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

plugins:
  - search
  - mermaid2:
      version: 8.6.4
      arguments:
          theme: 'neutral'
      
extra_javascript:
    - https://unpkg.com/mermaid@8.7.0/dist/mermaid.min.js
